import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BlogPreview from "@/Components/blogPreview";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
      <div id="blogbody">
        // somewhere in the return statement
        {blogs.map(
          (blog) => (
            <BlogPreview />
          ) // This is how we call the component
        )}
      </div>
      <script src="src/script.js"></script>
      <footer>© 2023 Turkish Delight | All Rights Reserved</footer>
    </html>
  );
}
